'use strict';

/**
 * Prompt-Katalog
 * Jede Vorlage setzt alle Formularfelder auf sinnvolle Standardwerte.
 * Neue Vorlagen einfach als weiteres Objekt ans Array anhängen.
 */
const PROMPT_CATALOG = [

  // ── Content ──────────────────────────────────────────────────────────────
  {
    id: 'seo-blogartikel',
    name: 'SEO-Blogartikel',
    icon: 'fa-solid fa-magnifying-glass',
    category: 'Content',
    descriptionHint: 'Thema des Artikels, Hauptkeyword, gewünschte Suchintention …',
    fields: {
      'content-type':          'Blog-Post',
      'content-length':        'Mittellange Absätze oder kurze Absätze mit mehreren Sätzen',
      'target-audience':       'Allgemeininteressierte Leser',
      'language-style':        'Journalistisch',
      'perspective':           'Neutral/Objektiv',
      'emoji-option':          'keine',
      'address-form':          'neutral',
      'formatting':            'Bullet Points',
      'seo-keyword-option':    'Ja',
      'title-subtitle-option': 'ja',
    },
  },
  {
    id: 'whitepaper',
    name: 'Whitepaper',
    icon: 'fa-solid fa-file-lines',
    category: 'Content',
    descriptionHint: 'Fachthema, Problemstellung, Kernthese und Zielsetzung …',
    fields: {
      'content-type':          'Whitepaper',
      'content-length':        'Sehr lange Absätze oder mehrere Absätze in Folge',
      'target-audience':       'Fachleute und Experten',
      'language-style':        'Technisch',
      'perspective':           'Neutral/Objektiv',
      'emoji-option':          'keine',
      'address-form':          'formal',
      'formatting':            'Nummerierte Liste',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'ja',
    },
  },
  {
    id: 'pressemitteilung',
    name: 'Pressemitteilung',
    icon: 'fa-solid fa-newspaper',
    category: 'Content',
    descriptionHint: 'Anlass, Unternehmen, Kernbotschaft und Zitat …',
    fields: {
      'content-type':          'Pressemitteilung',
      'content-length':        'Kurze Absätze oder längere Sätze',
      'target-audience':       'Allgemeininteressierte Leser',
      'language-style':        'Journalistisch',
      'perspective':           'Er-/Sie-Perspektive',
      'emoji-option':          'keine',
      'address-form':          'neutral',
      'formatting':            'Text',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'ja',
    },
  },
  {
    id: 'youtube-beschreibung',
    name: 'YouTube-Beschreibung',
    icon: 'fa-brands fa-youtube',
    category: 'Content',
    descriptionHint: 'Video-Thema, Hauptinhalt, Keywords und Links …',
    fields: {
      'content-type':          'YouTube-Video',
      'content-length':        'Mittellange Absätze oder kurze Absätze mit mehreren Sätzen',
      'target-audience':       'Allgemeininteressierte Leser',
      'language-style':        'Informell',
      'perspective':           'Wir-Perspektive',
      'emoji-option':          'wenige',
      'address-form':          'informell',
      'formatting':            'Text',
      'seo-keyword-option':    'Ja',
      'title-subtitle-option': 'ja',
    },
  },

  // ── Social Media ─────────────────────────────────────────────────────────
  {
    id: 'linkedin-post',
    name: 'LinkedIn-Post',
    icon: 'fa-brands fa-linkedin',
    category: 'Social Media',
    descriptionHint: 'Thema, persönliche Erfahrung oder beruflicher Insight …',
    fields: {
      'content-type':          'LinkedIn-Beitrag',
      'content-length':        'Kurze Absätze oder längere Sätze',
      'target-audience':       'Geschäftliche Zielgruppen',
      'language-style':        'Persönlich',
      'perspective':           'Ich-Perspektive',
      'emoji-option':          'wenige',
      'address-form':          'informell',
      'formatting':            'Bullet Points',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'nein',
    },
  },
  {
    id: 'instagram-caption',
    name: 'Instagram-Caption',
    icon: 'fa-brands fa-instagram',
    category: 'Social Media',
    descriptionHint: 'Bild-Inhalt, Stimmung, Produkt oder Erlebnis …',
    fields: {
      'content-type':          'Instagram-Beitrag',
      'content-length':        'Kurze, prägnante Sätze oder Fragen',
      'target-audience':       'Allgemeininteressierte Leser',
      'language-style':        'Informell',
      'perspective':           'Ich-Perspektive',
      'emoji-option':          'viele',
      'address-form':          'informell',
      'formatting':            'Text',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'nein',
    },
  },
  {
    id: 'twitter-post',
    name: 'Twitter / X-Post',
    icon: 'fa-brands fa-x-twitter',
    category: 'Social Media',
    descriptionHint: 'Kernaussage, Meinung oder Frage (max. 280 Zeichen) …',
    fields: {
      'content-type':          'Twitter-Beitrag',
      'content-length':        'Kurze, prägnante Sätze oder Fragen',
      'target-audience':       'Allgemeininteressierte Leser',
      'language-style':        'Informell',
      'perspective':           'Ich-Perspektive',
      'emoji-option':          'wenige',
      'address-form':          'informell',
      'formatting':            'Text',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'nein',
    },
  },
  {
    id: 'facebook-beitrag',
    name: 'Facebook-Beitrag',
    icon: 'fa-brands fa-facebook',
    category: 'Social Media',
    descriptionHint: 'Thema, Community-Frage oder Ankündigung …',
    fields: {
      'content-type':          'Facebook-Beitrag',
      'content-length':        'Kurze Absätze oder längere Sätze',
      'target-audience':       'Allgemeininteressierte Leser',
      'language-style':        'Informell',
      'perspective':           'Wir-Perspektive',
      'emoji-option':          'wenige',
      'address-form':          'informell',
      'formatting':            'Text',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'nein',
    },
  },

  // ── Marketing ────────────────────────────────────────────────────────────
  {
    id: 'produktbeschreibung',
    name: 'Produktbeschreibung',
    icon: 'fa-solid fa-tag',
    category: 'Marketing',
    descriptionHint: 'Produktname, Eigenschaften, Vorteile und Zielkunde …',
    fields: {
      'content-type':          'Produktbeschreibung',
      'content-length':        'Kurze Absätze oder längere Sätze',
      'target-audience':       'Leser mit bestimmten Interessen',
      'language-style':        'Werblich',
      'perspective':           'Du-Perspektive',
      'emoji-option':          'keine',
      'address-form':          'informell',
      'formatting':            'Bullet Points',
      'seo-keyword-option':    'Ja',
      'title-subtitle-option': 'ja',
    },
  },
  {
    id: 'newsletter',
    name: 'Newsletter',
    icon: 'fa-solid fa-envelope-open-text',
    category: 'Marketing',
    descriptionHint: 'Thema der Ausgabe, Ankündigungen, Highlights …',
    fields: {
      'content-type':          'Newsletter',
      'content-length':        'Kurze Absätze oder längere Sätze',
      'target-audience':       'Leser mit bestimmten Interessen',
      'language-style':        'Persönlich',
      'perspective':           'Wir-Perspektive',
      'emoji-option':          'wenige',
      'address-form':          'informell',
      'formatting':            'Text',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'ja',
    },
  },
  {
    id: 'landing-page',
    name: 'Landing Page',
    icon: 'fa-solid fa-rectangle-ad',
    category: 'Marketing',
    descriptionHint: 'Produkt/Dienstleistung, USP, gewünschte Zielhandlung …',
    fields: {
      'content-type':          'Landing Page',
      'content-length':        'Kurze, prägnante Sätze oder Fragen',
      'target-audience':       'Leser mit bestimmten Interessen',
      'language-style':        'Werblich',
      'perspective':           'Du-Perspektive',
      'emoji-option':          'keine',
      'address-form':          'informell',
      'formatting':            'Bullet Points',
      'seo-keyword-option':    'Ja',
      'title-subtitle-option': 'ja',
    },
  },

  // ── E-Mail ───────────────────────────────────────────────────────────────
  {
    id: 'kalt-akquise',
    name: 'Kalt-Akquise E-Mail',
    icon: 'fa-solid fa-paper-plane',
    category: 'E-Mail',
    descriptionHint: 'Unternehmen, Angebot, Ansprechpartner und Nutzenversprechen …',
    fields: {
      'content-type':          'E-Mail',
      'content-length':        'Kurze Absätze oder längere Sätze',
      'target-audience':       'Geschäftliche Zielgruppen',
      'language-style':        'Formell',
      'perspective':           'Ich-Perspektive',
      'emoji-option':          'keine',
      'address-form':          'formal',
      'formatting':            'Text',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'nein',
    },
  },
  {
    id: 'follow-up',
    name: 'Follow-Up E-Mail',
    icon: 'fa-solid fa-reply',
    category: 'E-Mail',
    descriptionHint: 'Vorheriger Kontakt, offene Punkte, nächster Schritt …',
    fields: {
      'content-type':          'E-Mail',
      'content-length':        'Kurze, prägnante Sätze oder Fragen',
      'target-audience':       'Geschäftliche Zielgruppen',
      'language-style':        'Persönlich',
      'perspective':           'Ich-Perspektive',
      'emoji-option':          'keine',
      'address-form':          'formal',
      'formatting':            'Text',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'nein',
    },
  },
  {
    id: 'angebots-email',
    name: 'Angebots-E-Mail',
    icon: 'fa-solid fa-percent',
    category: 'E-Mail',
    descriptionHint: 'Angebot, Preisvorteile, Gültigkeitsdauer …',
    fields: {
      'content-type':          'E-Mail',
      'content-length':        'Kurze Absätze oder längere Sätze',
      'target-audience':       'Leser mit bestimmten Interessen',
      'language-style':        'Werblich',
      'perspective':           'Wir-Perspektive',
      'emoji-option':          'wenige',
      'address-form':          'informell',
      'formatting':            'Bullet Points',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'ja',
    },
  },

];
