'use strict';

/**
 * Prompt-Katalog
 * Jede Vorlage setzt alle Formularfelder auf sinnvolle Standardwerte.
 * Neue Vorlagen einfach als weiteres Objekt ans Array anhängen.
 *
 * Felder:
 *   id                   – eindeutige ID (kebab-case)
 *   name                 – Anzeigename
 *   icon                 – Font Awesome 6 Klasse
 *   category             – Content | Social Media | Marketing | E-Mail
 *   descriptionHint      – Platzhaltertext fürs Beschreibungsfeld
 *   fields               – Voreinstellungen für alle Formularfelder
 */
const PROMPT_CATALOG = [

  // ── Content ──────────────────────────────────────────────────────────────
  {
    id: 'seo-blogartikel',
    name: 'SEO-Blogartikel',
    icon: 'fa-solid fa-magnifying-glass',
    category: 'Content',
    descriptionHint: 'Thema des Artikels, Hauptkeyword, gewünschte Suchintention …',
    fields: {
      'content-type':          'Blog-Post',
      'content-length':        'Mittel (300–600 Wörter)',
      'target-audience':       'Berufstätige (30–50 Jahre)',
      'language-style':        'Journalistisch',
      'perspective':           'Neutral/Objektiv',
      'emoji-option':          'keine',
      'address-form':          'neutral',
      'formatting':            'Bullet Points',
      'seo-keyword-option':    'Ja',
      'title-subtitle-option': 'ja',
      'beispiel': '',
    },
  },
  {
    id: 'whitepaper',
    name: 'Whitepaper',
    icon: 'fa-solid fa-file-lines',
    category: 'Content',
    descriptionHint: 'Fachthema, Problemstellung, Kernthese und Zielsetzung …',
    fields: {
      'content-type':          'Whitepaper',
      'content-length':        'Sehr lang (1.200+ Wörter)',
      'target-audience':       'B2B-Entscheider',
      'language-style':        'Technisch',
      'perspective':           'Neutral/Objektiv',
      'emoji-option':          'keine',
      'address-form':          'formal',
      'formatting':            'Nummerierte Liste',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'ja',
      'beispiel': '',
    },
  },
  {
    id: 'pressemitteilung',
    name: 'Pressemitteilung',
    icon: 'fa-solid fa-newspaper',
    category: 'Content',
    descriptionHint: 'Anlass, Unternehmen, Kernbotschaft und Zitat …',
    fields: {
      'content-type':          'Pressemitteilung',
      'content-length':        'Kurz (100–300 Wörter)',
      'target-audience':       'Berufstätige (30–50 Jahre)',
      'language-style':        'Journalistisch',
      'perspective':           'Er-/Sie-Perspektive',
      'emoji-option':          'keine',
      'address-form':          'neutral',
      'formatting':            'Fließtext',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'ja',
      'beispiel': '',
    },
  },
  {
    id: 'youtube-beschreibung',
    name: 'YouTube-Beschreibung',
    icon: 'fa-brands fa-youtube',
    category: 'Content',
    descriptionHint: 'Video-Thema, Hauptinhalt, Keywords und Links …',
    fields: {
      'content-type':          'YouTube-Video',
      'content-length':        'Mittel (300–600 Wörter)',
      'target-audience':       'Berufstätige (30–50 Jahre)',
      'language-style':        'Informell',
      'perspective':           'Wir-Perspektive',
      'emoji-option':          'wenige',
      'address-form':          'informell',
      'formatting':            'Fließtext',
      'seo-keyword-option':    'Ja',
      'title-subtitle-option': 'ja',
      'beispiel': '',
    },
  },

  {
    id: 'howto-artikel',
    name: 'How-To Artikel',
    icon: 'fa-solid fa-list-check',
    category: 'Content',
    descriptionHint: 'Was soll erklärt werden? Für wen? Welches Problem wird gelöst? …',
    fields: {
      'content-type':          'How-to-Anleitung',
      'content-length':        'Mittel (300–600 Wörter)',
      'target-audience':       'Berufstätige (30–50 Jahre)',
      'language-style':        'Sachlich',
      'perspective':           'Neutral/Objektiv',
      'emoji-option':          'keine',
      'address-form':          'informell',
      'formatting':            'Schritt-für-Schritt',
      'seo-keyword-option':    'Ja',
      'title-subtitle-option': 'ja',
      'beispiel': '',
    },
  },
  {
    id: 'case-study',
    name: 'Case Study',
    icon: 'fa-solid fa-chart-line',
    category: 'Content',
    descriptionHint: 'Kundenname, Problem, Lösung, messbare Ergebnisse und Zitat …',
    fields: {
      'content-type':          'Case-Study',
      'content-length':        'Lang (600–1.200 Wörter)',
      'target-audience':       'B2B-Entscheider',
      'language-style':        'Sachlich',
      'perspective':           'Er-/Sie-Perspektive',
      'emoji-option':          'keine',
      'address-form':          'formal',
      'formatting':            'Überschriften + Fließtext',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'ja',
      'beispiel': '',
    },
  },
  {
    id: 'podcast-outline',
    name: 'Podcast-Folge',
    icon: 'fa-solid fa-microphone-lines',
    category: 'Content',
    descriptionHint: 'Folgentitel, Hauptthema, Gast (falls vorhanden), 3 Kernpunkte …',
    fields: {
      'content-type':          'Podcast-Episode',
      'content-length':        'Mittel (300–600 Wörter)',
      'target-audience':       'Junge Erwachsene (25–35 Jahre)',
      'language-style':        'Persönlich',
      'perspective':           'Wir-Perspektive',
      'emoji-option':          'keine',
      'address-form':          'informell',
      'formatting':            'Nummerierte Liste',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'ja',
      'beispiel': '',
    },
  },

  // ── Social Media ─────────────────────────────────────────────────────────
  {
    id: 'linkedin-post',
    name: 'LinkedIn-Post',
    icon: 'fa-brands fa-linkedin',
    category: 'Social Media',
    descriptionHint: 'Thema, persönliche Erfahrung oder beruflicher Insight …',
    fields: {
      'content-type':          'LinkedIn-Beitrag',
      'content-length':        'Kurz (100–300 Wörter)',
      'target-audience':       'Manager & Führungskräfte',
      'language-style':        'Persönlich',
      'perspective':           'Ich-Perspektive',
      'emoji-option':          'wenige',
      'address-form':          'informell',
      'formatting':            'Bullet Points',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'nein',
      'beispiel': '',
    },
  },
  {
    id: 'instagram-caption',
    name: 'Instagram-Caption',
    icon: 'fa-brands fa-instagram',
    category: 'Social Media',
    descriptionHint: 'Bild-Inhalt, Stimmung, Produkt oder Erlebnis …',
    fields: {
      'content-type':          'Instagram-Beitrag',
      'content-length':        'Sehr kurz (50–100 Wörter)',
      'target-audience':       'Junge Erwachsene (25–35 Jahre)',
      'language-style':        'Informell',
      'perspective':           'Ich-Perspektive',
      'emoji-option':          'viele',
      'address-form':          'informell',
      'formatting':            'Fließtext',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'nein',
      'beispiel': '',
    },
  },
  {
    id: 'twitter-post',
    name: 'Twitter / X-Post',
    icon: 'fa-brands fa-x-twitter',
    category: 'Social Media',
    descriptionHint: 'Kernaussage, Meinung oder Frage (max. 280 Zeichen) …',
    fields: {
      'content-type':          'Twitter-Beitrag',
      'content-length':        'Sehr kurz (50–100 Wörter)',
      'target-audience':       'Junge Erwachsene (25–35 Jahre)',
      'language-style':        'Informell',
      'perspective':           'Ich-Perspektive',
      'emoji-option':          'wenige',
      'address-form':          'informell',
      'formatting':            'Fließtext',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'nein',
      'beispiel': '',
    },
  },
  {
    id: 'facebook-beitrag',
    name: 'Facebook-Beitrag',
    icon: 'fa-brands fa-facebook',
    category: 'Social Media',
    descriptionHint: 'Thema, Community-Frage oder Ankündigung …',
    fields: {
      'content-type':          'Facebook-Beitrag',
      'content-length':        'Kurz (100–300 Wörter)',
      'target-audience':       'Berufstätige (30–50 Jahre)',
      'language-style':        'Informell',
      'perspective':           'Wir-Perspektive',
      'emoji-option':          'wenige',
      'address-form':          'informell',
      'formatting':            'Fließtext',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'nein',
      'beispiel': '',
    },
  },

  {
    id: 'tiktok-skript',
    name: 'TikTok-Skript',
    icon: 'fa-brands fa-tiktok',
    category: 'Social Media',
    descriptionHint: 'Hook (erste 3 Sek.), Hauptbotschaft, Call-to-Action, Trend oder Sound …',
    fields: {
      'content-type':          'TikTok-Skript',
      'content-length':        'Sehr kurz (50–100 Wörter)',
      'target-audience':       'Jugendliche (16–25 Jahre)',
      'language-style':        'Humorvoll',
      'perspective':           'Ich-Perspektive',
      'emoji-option':          'viele',
      'address-form':          'informell',
      'formatting':            'Schritt-für-Schritt',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'nein',
      'beispiel': '',
    },
  },
  {
    id: 'xing-beitrag',
    name: 'Xing-Beitrag',
    icon: 'fa-brands fa-xing',
    category: 'Social Media',
    descriptionHint: 'Beruflicher Insight, Projekt-Update, Branchennews oder Karrieretipp …',
    fields: {
      'content-type':          'Xing-Beitrag',
      'content-length':        'Kurz (100–300 Wörter)',
      'target-audience':       'Manager & Führungskräfte',
      'language-style':        'Seriös',
      'perspective':           'Ich-Perspektive',
      'emoji-option':          'keine',
      'address-form':          'formal',
      'formatting':            'Fließtext',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'nein',
      'beispiel': '',
    },
  },

  // ── Marketing ────────────────────────────────────────────────────────────
  {
    id: 'produktbeschreibung',
    name: 'Produktbeschreibung',
    icon: 'fa-solid fa-tag',
    category: 'Marketing',
    descriptionHint: 'Produktname, Eigenschaften, Vorteile und Zielkunde …',
    fields: {
      'content-type':          'Produktbeschreibung',
      'content-length':        'Kurz (100–300 Wörter)',
      'target-audience':       'Berufstätige (30–50 Jahre)',
      'language-style':        'Werblich',
      'perspective':           'Du-Perspektive',
      'emoji-option':          'keine',
      'address-form':          'informell',
      'formatting':            'Bullet Points',
      'seo-keyword-option':    'Ja',
      'title-subtitle-option': 'ja',
      'beispiel': '',
    },
  },
  {
    id: 'newsletter',
    name: 'Newsletter',
    icon: 'fa-solid fa-envelope-open-text',
    category: 'Marketing',
    descriptionHint: 'Thema der Ausgabe, Ankündigungen, Highlights …',
    fields: {
      'content-type':          'Newsletter',
      'content-length':        'Kurz (100–300 Wörter)',
      'target-audience':       'Berufstätige (30–50 Jahre)',
      'language-style':        'Persönlich',
      'perspective':           'Wir-Perspektive',
      'emoji-option':          'wenige',
      'address-form':          'informell',
      'formatting':            'Fließtext',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'ja',
      'beispiel': '',
    },
  },
  {
    id: 'landing-page',
    name: 'Landing Page',
    icon: 'fa-solid fa-rectangle-ad',
    category: 'Marketing',
    descriptionHint: 'Produkt/Dienstleistung, USP, gewünschte Zielhandlung …',
    fields: {
      'content-type':          'Landing Page',
      'content-length':        'Sehr kurz (50–100 Wörter)',
      'target-audience':       'Berufstätige (30–50 Jahre)',
      'language-style':        'Werblich',
      'perspective':           'Du-Perspektive',
      'emoji-option':          'keine',
      'address-form':          'informell',
      'formatting':            'Bullet Points',
      'seo-keyword-option':    'Ja',
      'title-subtitle-option': 'ja',
      'beispiel': '',
    },
  },

  {
    id: 'faq-seite',
    name: 'FAQ-Seite',
    icon: 'fa-solid fa-circle-question',
    category: 'Marketing',
    descriptionHint: 'Produkt/Service, häufige Kundenfragen, typische Einwände …',
    fields: {
      'content-type':          'FAQ-Seite',
      'content-length':        'Mittel (300–600 Wörter)',
      'target-audience':       'Berufstätige (30–50 Jahre)',
      'language-style':        'Sachlich',
      'perspective':           'Neutral/Objektiv',
      'emoji-option':          'keine',
      'address-form':          'informell',
      'formatting':            'Nummerierte Liste',
      'seo-keyword-option':    'Ja',
      'title-subtitle-option': 'nein',
      'beispiel': '',
    },
  },

  // ── E-Mail ───────────────────────────────────────────────────────────────
  {
    id: 'kalt-akquise',
    name: 'Kalt-Akquise E-Mail',
    icon: 'fa-solid fa-paper-plane',
    category: 'E-Mail',
    descriptionHint: 'Unternehmen, Angebot, Ansprechpartner und Nutzenversprechen …',
    fields: {
      'content-type':          'Kaltakquise-E-Mail',
      'content-length':        'Kurz (100–300 Wörter)',
      'target-audience':       'B2B-Entscheider',
      'language-style':        'Formell',
      'perspective':           'Ich-Perspektive',
      'emoji-option':          'keine',
      'address-form':          'formal',
      'formatting':            'Fließtext',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'nein',
      'beispiel': '',
    },
  },
  {
    id: 'follow-up',
    name: 'Follow-Up E-Mail',
    icon: 'fa-solid fa-reply',
    category: 'E-Mail',
    descriptionHint: 'Vorheriger Kontakt, offene Punkte, nächster Schritt …',
    fields: {
      'content-type':          'Follow-up-E-Mail',
      'content-length':        'Sehr kurz (50–100 Wörter)',
      'target-audience':       'B2B-Entscheider',
      'language-style':        'Persönlich',
      'perspective':           'Ich-Perspektive',
      'emoji-option':          'keine',
      'address-form':          'formal',
      'formatting':            'Fließtext',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'nein',
      'beispiel': '',
    },
  },
  {
    id: 'angebots-email',
    name: 'Angebots-E-Mail',
    icon: 'fa-solid fa-percent',
    category: 'E-Mail',
    descriptionHint: 'Angebot, Preisvorteile, Gültigkeitsdauer …',
    fields: {
      'content-type':          'E-Mail',
      'content-length':        'Kurz (100–300 Wörter)',
      'target-audience':       'Berufstätige (30–50 Jahre)',
      'language-style':        'Werblich',
      'perspective':           'Wir-Perspektive',
      'emoji-option':          'wenige',
      'address-form':          'informell',
      'formatting':            'Bullet Points',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'ja',
      'beispiel': '',
    },
  },

  {
    id: 'onboarding-email',
    name: 'Onboarding E-Mail',
    icon: 'fa-solid fa-handshake',
    category: 'E-Mail',
    descriptionHint: 'Produkt/Service, erste Schritte, wichtigste Features, Support-Kontakt …',
    fields: {
      'content-type':          'Onboarding-E-Mail',
      'content-length':        'Kurz (100–300 Wörter)',
      'target-audience':       'Berufstätige (30–50 Jahre)',
      'language-style':        'Persönlich',
      'perspective':           'Wir-Perspektive',
      'emoji-option':          'wenige',
      'address-form':          'informell',
      'formatting':            'Schritt-für-Schritt',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'nein',
      'beispiel': '',
    },
  },
  {
    id: 'feedback-anfrage',
    name: 'Feedback-Anfrage',
    icon: 'fa-solid fa-star-half-stroke',
    category: 'E-Mail',
    descriptionHint: 'Produkt/Service, Kaufdatum oder Nutzungsdauer, gewünschte Plattform (Google, Trustpilot …) …',
    fields: {
      'content-type':          'E-Mail',
      'content-length':        'Sehr kurz (50–100 Wörter)',
      'target-audience':       'Berufstätige (30–50 Jahre)',
      'language-style':        'Persönlich',
      'perspective':           'Wir-Perspektive',
      'emoji-option':          'keine',
      'address-form':          'informell',
      'formatting':            'Fließtext',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'nein',
      'beispiel': '',
    },
  },

  // ── Business ─────────────────────────────────────────────────────────────
  {
    id: 'praesentation',
    name: 'Präsentation',
    icon: 'fa-solid fa-display',
    category: 'Business',
    descriptionHint: 'Thema, Ziel der Präsentation, Zuhörer, Anzahl Folien (ca.), Kernbotschaft …',
    fields: {
      'content-type':          'Präsentation',
      'content-length':        'Mittel (300–600 Wörter)',
      'target-audience':       'Manager & Führungskräfte',
      'language-style':        'Sachlich',
      'perspective':           'Wir-Perspektive',
      'emoji-option':          'keine',
      'address-form':          'formal',
      'formatting':            'Nummerierte Liste',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'ja',
      'beispiel': '',
    },
  },
  {
    id: 'stellenanzeige',
    name: 'Stellenanzeige',
    icon: 'fa-solid fa-briefcase',
    category: 'Business',
    descriptionHint: 'Position, Unternehmen, Aufgaben, Anforderungen, Benefits und Unternehmenskultur …',
    fields: {
      'content-type':          'Stellenanzeige',
      'content-length':        'Mittel (300–600 Wörter)',
      'target-audience':       'Berufstätige (30–50 Jahre)',
      'language-style':        'Inspirierend',
      'perspective':           'Wir-Perspektive',
      'emoji-option':          'wenige',
      'address-form':          'informell',
      'formatting':            'Bullet Points',
      'seo-keyword-option':    'Ja',
      'title-subtitle-option': 'ja',
      'beispiel': '',
    },
  },
  {
    id: 'bewerbungsschreiben',
    name: 'Bewerbungsschreiben',
    icon: 'fa-solid fa-file-signature',
    category: 'Business',
    descriptionHint: 'Angestrebte Stelle, Unternehmen, eigene Stärken, relevante Erfahrungen, Motivation …',
    fields: {
      'content-type':          'Bewerbungsschreiben',
      'content-length':        'Kurz (100–300 Wörter)',
      'target-audience':       'B2B-Entscheider',
      'language-style':        'Formell',
      'perspective':           'Ich-Perspektive',
      'emoji-option':          'keine',
      'address-form':          'formal',
      'formatting':            'Fließtext',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'nein',
      'beispiel': '',
    },
  },
  {
    id: 'angebot-proposal',
    name: 'Angebot / Proposal',
    icon: 'fa-solid fa-file-invoice',
    category: 'Business',
    descriptionHint: 'Kunde, Problemstellung, angebotene Lösung, Leistungsumfang, Preis und Zeitplan …',
    fields: {
      'content-type':          'Angebot / Proposal',
      'content-length':        'Lang (600–1.200 Wörter)',
      'target-audience':       'B2B-Entscheider',
      'language-style':        'Seriös',
      'perspective':           'Wir-Perspektive',
      'emoji-option':          'keine',
      'address-form':          'formal',
      'formatting':            'Überschriften + Fließtext',
      'seo-keyword-option':    'Nein',
      'title-subtitle-option': 'ja',
      'beispiel': '',
    },
  },

];
